blank_issues_enabled: false
contact_links:
  - name: Curseforge
    url: https://www.curseforge.com/minecraft/modpacks/automate
    about: Support the project on Curseforge
  - name: Github Issues
    url: https://github.com/ralphschuler/Automate/issues
    about: Please check for related issues before opening a new one.